import { Open_Sans, DM_Sans, Outfit, Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/Header/Header";
import Footer from "@/components/shared/Footer/Footer";

// Load fonts using next/font
const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

const outfit = Outfit({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${dmSans.variable} ${outfit.variable} ${roboto.variable}`}
      >
        <div className="app-container">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
